export const GET_CHOCLATE ="GET_CHOCLATE"
export const GET_CHOCLATE_SUCCESS ="GET_CHOCLATE_SUCCESS"
export const GET_CHOCLATE_FAILURE ="GET_CHOCLATE_FAILURE"


export const GET_CHOCLATE_DETAILS ="GET_CHOCLATE_DETAILS"
export const GET_CHOCLATE_DETAILS_SUCCESS ="GET_CHOCLATE_DETAILS_SUCCESS"
export const GET_CHOCLATE_DETAILS_FAILURE ="GET_CHOCLATE_DETAILS_FAILURE"
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_SUCCESS ="GET_BRAND_SUCCESS"
export const GET_BRAND_FAILURE ="GET_CHOCLATE_FAILURE"

 
export const GET_BRAND_DETAILS ="GET_BRAND_DETAILS"
export const GET_BRAND_DETAILS_SUCCESS ="GET_BRAND_DETAILS_SUCCESS"
export const GET_BRAND_DETAILS_FAILURE ="GET_BRAND_DETAILS_FAILURE"

