export const GET_LOGIN ="GET_LOGIN"
export const GET_LOGIN_SUCCESS ="GET_LOGIN_SUCCESS"
export const GET_LOGIN_FAILURE ="GET_LOGIN_FAILURE"
export const CHANGE_INPUT = "CHANGE_INPUT"

// export const GET_LOGIN_DETAILS ="GET_LOGIN_DETAILS"
// export const GET_LOGIN_DETAILS_SUCCESS ="GET_LOGIN_DETAILS_SUCCESS"
// export const GET_LOGIN_DETAILS_FAILURE ="GET_LOGIN_DETAILS_FAILURE"

export const GET_SIGNUP = "GET_SIGNUP"
export const GET_SIGNUP_SUCCESS ="GET_SIGNUP_SUCCESS"
export const GET_SIGNUP_FAILURE ="GET_SIGNUP_FAILURE"

export const GET_SEARCH = "GET_SEARCH"
export const GET_SEARCH_SUCCESS="GET_SEARCH_SUCCESS"
export const GET_SERCH_FAILURE="GET_SEARCH_FAILURE"

 
// export const GET_SIGNUP_DETAILS ="GET_SIGNUP_DETAILS"
// export const GET_SIGNUP_DETAILS_SUCCESS ="GET_SIGNUP_DETAILS_SUCCESS"
// export const GET_SIGNUP_DETAILS_FAILURE ="GET_SIGNUP_DETAILS_FAILURE"

